### ISSUE TITLE
釣りビジョン アニマックス

### ISSUE THREAD

**Issue by pcyookies** [stz2012/recpt1#18]
{   1, CHTYPE_SATELLITE, 0, "191"},  /* 191ch：WOWOW prime */
{   1, CHTYPE_SATELLITE, 1, "236"},  /* 236ch：BSアニマックス */
{   1, CHTYPE_SATELLITE, 2, "251"},  /* 251ch：BS釣りビジョン */

**Comment by stz2012** [comment]
https://github.com/stz2012/recpt1/pull/19
上記にて対応
